package:
  name: my-snakemake-tool
  version: "0.1.0"

source:
  path: .  # 如果直接在项目根目录下放 meta.yaml，表示从当前目录构建

build:
  number: 0
  noarch: generic  # 如果你的工具不依赖特定架构（如纯 Python 或 Snakemake 脚本）
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - snakemake >=7.0.0
    - pandas >=2.3.0
    - openpyxl >=3.1.5
    - 其他你的工具依赖，比如 pandas, numpy 等

about:
  license: MIT
  summary: "一个使用 Snakemake 构建的生物信息学工具"