name: rubberband
channels:
  - default
  - conda-forge
  - bioconda
dependencies:
  - snakemake=9.5.1
  - python=3.11.9
  - pandas=2.2.3
  - openpyxl=3.1.0
  - abricate=1.0.1
  - kofamscan=1.2.0